### PR TITLE
Support oci sync

### LINKED ISSUE #100: unsupported manifest type: application/vnd.oci.image.manifest.v1+json
Bug Report
---

Type: *bug report*

### What happened

I got such error when syncing knative images from gcr.io

ERRO[2022-06-02 15:30:19] Get blob info from gcr.io/knative-releases/knative.dev/client/cmd/kn:sha256-7954fe11a6dce1ec92f77355f2d8438dc39a0e34195e294becb9f70631397ca3.sbom error: unsupported manifest type: application/vnd.oci.image.manifest.v1+json

### Environment
- image-syncer version:
- OS (e.g. `cat /etc/os-release`):
- Registry version (e.g. `habor`):
- Others:

### PR DESCRIPTION
**Pull request by lujiajing1126**
Pull Request Description
---

### Describe what this PR does / why we need it

This PR add support for OCI image specs

### Does this pull request fix one issue?

Fixes #100 

### Special notes for reviews

### CODE REVIEW

**Comment by htlabc** [comment]
This PR add can't support for OCI image specs,when you push oci media type to harbor will get some error

**Comment by lujiajing1126** [comment]
> This PR add can't support for OCI image specs,when you push oci media type to harbor will get some error

Well, your destination must support OCI, for example, JFrog Artifactory. From the official Habor blog, https://goharbor.io/blog/harbor-2.0/, it starts to support OCI from 2.0.

Otherwise, you may have to transform from DockerImage to OCI image locally.

**Comment by lujiajing1126** [comment]
> The letest image syncer where can download，can slove application/vnd.oci.image.manifest.v1+json

Not pretty catch your meaning. But if you want a working binary, you may clone my fork https://github.com/lujiajing1126/image-syncer and build on your server.

**Review by hhyasdf — APPROVED** [review]
/lgtm

**Pull request merged**
