### PR TITLE
refactor to make cmd clean phony

### PR DESCRIPTION
**Pull request by andy2046**
Hi @hhyasdf I would like to submit a small PR for the issue I encounter while using it in Kubernetes, the container pod keep restarting after sync task completion, which triggers a lot of false alerts for monitoring, therefore to enable recurring for sync task

#### changes made: ####

- [x] refactor: enable recurring for sync task, so no container pod restarts after sync task completion
- [x] refactor: make cmd clean phony to skip `make 'cmd' is up to date.` issue

### CODE REVIEW

**Comment by hhyasdf** [comment]
Can you just describe the usage more clearly? It's not supposed to restart after all the sync tasks are completed, unless the container becomes a pod of deployment in Kubernetes, it will be restarted by deployment controller automatically.

**Comment by andy2046** [comment]
Hi @hhyasdf, when I do `docker run`, it just complete and exit the process, but in k8s, as you said, the controller treat it as container stopped and try to re-create the container again in the pod, and thus it adds a lot of container re-create in log monitoring, so it's better to add option to keep the process running till it's killed by os.signal,

by default it still run as one time task

hope this clarifies my use case clearly

**Comment by hhyasdf** [comment]
Well, in Kubernetes, I think it's supposed to run a Job rather than a Deployment or other workloads if you just want to run a Pod for only once. 

I don't think it's properly to add such logic in image-syncer's source code, cause it should not be considered by this tool itself, run it as a Job should be a good solution for you.

**Comment by andy2046** [comment]
for k8s we can use Job rather than Deployment, but how about non-k8s scenarios? in some VM we just run docker and docker process will run and exit, if we use crontab to schedule it, it may end up with 2 concurrent jobs running, with this option, at least we do not have concurrent running jobs issue

**Comment by hhyasdf** [comment]
I still don't know why you are worry about these script things after understanding your code. You can get what you want for a simple shell script which just use the "sleep" command with a for loop, even with other linux commands that fit it.

And I think it's more graceful to add a "daemon mode" to image-syncer (that's a plan for us) rather than keep the code which is not necessary inside the project.

**Comment by andy2046** [comment]
noted, thx

**Comment by hhyasdf** [comment]
Thanks so much for your contribution! How about making an issue before we want to add a feature? So that we can have an adequate discussion. 

thx again.

**Comment by andy2046** [comment]
will raise an issue next time to discuss the feature, thanks

**Pull request merged**
