### PR TITLE
Solve the external call method of Client struct

### PR DESCRIPTION
**Pull request by weiqiang333**
Pull Request Description
---

### Describe what this PR does / why we need it
The external warehouse import "github.com/AliyunContainerService/image-syncer/pkg/client", When you want to do something, you can customize the NewSyncClient.
For example, I want to provide a custom image-rsync-service

### Does this pull request fix one issue?
For example, I want to provide a custom image-rsync-service

### Describe how you did it
I will provide its services: https://github.com/weiqiang333/imagersync-service

### Describe how to verify it
I performed local function verification

### Special notes for reviews

### CODE REVIEW

**Comment by hhyasdf** [comment]
Maybe it's better to add some methods for the fields you need rather than export them all.

**Comment by weiqiang333** [comment]
>

**Comment by weiqiang333** [comment]
> Maybe it's better to add some methods for the fields you need rather than export them all.

If I want to implement a custom client like this https://github.com/weiqiang333/imagersync-service/blob/19a4d50d674cf8e4748700ae4119e6f38dd76009/internal/imagersync/imagersync.go#L18

Instead of the current specific NewSyncClient 
https://github.com/AliyunContainerService/image-syncer/blob/f0b1b8cbc2c080002cf8fdf138a68bbdbfc1aef3/pkg/client/client.go#L46

I don't think you want me to create more wheels like NewSyncClient in AliyunContainerService/image-syncer
If you allow it to be exported, it will have more external extensibility
Will also conform to the PKG dir attribute

**Comment by hhyasdf** [comment]
Client is the entry that how image-syncer itself do image synchronization, and it's not propriate to just export all the feilds of "client.Client struct" for customization.

Now I minimize the "pkg/client" and make different functions apart, so you can use it freely.

**Pull request closed without merging**
